name: build .NET and deploy

on:
  push:
    branches: 
      - main
      - devops/ci-cd
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    # -------- 1 PHASE --------
      - name: Checkout repository
        uses: actions/checkout@v4